CREATE DATABASE IF NOT EXISTS productdb 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE productdb;

CREATE TABLE IF NOT EXISTS products (
    id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    purchaseDate VARCHAR(10) NOT NULL,
    store VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    userId CHAR(36) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;
